=== M1ztl/customerJaxb/HUE04_EMobilityJSF/data/emobility.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.emobility.org" xmlns="http://www.emobility.org" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="emobility" type="emobilityType"/>
  <xs:complexType name="addressType">
    <xs:sequence>
      <xs:element name="city" type="xs:string"/>
      <xs:element name="zip" type="xs:int"/>
      <xs:element name="street" type="xs:string"/>
      <xs:element name="streetNr" type="xs:int"/>
      <xs:element name="federalState" type="xs:string"/>
      <xs:element name="country">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="2"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="chargeType">
    <xs:sequence>
      <xs:element type="xs:long" name="startDate"/>
      <xs:element type="xs:long" name="endDate"/>
      <xs:element type="xs:double" name="duration"/>
      <xs:element type="xs:double" name="kwhCharged"/>
      <xs:element type="xs:double" name="pricePerKwh"/>
      <xs:element type="xs:double" name="total"/>
      <xs:element type="xs:long" name="userId"/>
      <xs:element type="xs:long" name="parkId"/>
      <xs:element type="xs:long" name="stationId"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="chargesType">
    <xs:sequence>
      <xs:element type="chargeType" name="charge" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="chargeManagerType">
    <xs:sequence>
      <xs:element type="chargesType" name="charges"/>
      <xs:element type="chargesType" name="activeCharges"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="chargingstationType">
    <xs:sequence>
      <xs:element name="id" type="xs:int"/>
      <xs:element name="connector">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Type 1"/>
            <xs:enumeration value="Type 2"/>
            <xs:enumeration value="3-pin plug"/>
            <xs:enumeration value="CHAdeMO"/>
            <xs:enumeration value="Combined Charging System"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:double" name="maxPowerOut"/>
      <xs:element type="xs:double" name="pricePerKwh"/>
      <xs:element type="xs:boolean" name="inUse"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="chargingstationsType">
    <xs:sequence>
      <xs:element type="chargingstationType" name="chargingstation" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="chargingparkType">
    <xs:sequence>
      <xs:element type="xs:long" name="id"/>
      <xs:element type="addressType" name="address"/>
      <xs:element type="chargingstationsType" name="chargingstations"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="chargingparksType">
    <xs:sequence>
      <xs:element type="chargingparkType" name="chargingpark" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="personType">
    <xs:sequence>
      <xs:element type="xs:long" name="id"/>
      <xs:element type="xs:string" name="firstname"/>
      <xs:element type="xs:string" name="lastname"/>
      <xs:element type="addressType" name="address"/>
      <xs:element type="xs:string" name="email"/>
      <xs:element type="xs:long" name="phone"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="memberType">
    <xs:complexContent>
      <xs:extension base="personType">
        <xs:sequence>
          <xs:element type="xs:boolean" name="active"/>
          <xs:element type="xs:long" name="dateRegistered"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="membersType">
    <xs:sequence>
      <xs:element type="memberType" name="member" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="employeeType">
    <xs:complexContent>
      <xs:extension base="personType">
        <xs:sequence>
          <xs:element type="xs:long" name="dateJoined"/>
          <xs:element type="xs:boolean" name="quitted"/>
          <xs:element type="xs:double" name="discount"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="employeesType">
    <xs:sequence>
      <xs:element type="employeeType" name="employee" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="operatorType">
    <xs:sequence>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="xs:string" name="email"/>
      <xs:element type="xs:long" name="phone"/>
      <xs:element type="chargingparksType" name="chargingparks"/>
      <xs:element type="membersType" name="members"/>
      <xs:element type="employeesType" name="employees"/>
      <xs:element type="addressType" name="address"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="emobilityType">
    <xs:sequence>
      <xs:element type="operatorType" name="operator"/>
      <xs:element type="chargeManagerType" name="chargeManager"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== M1ztl/customerJaxb/HUE04_EMobilityJSF/data/emobility.xml
<?xml version="1.0" encoding="UTF-8" ?>

<emobility xmlns="http://www.emobility.org"
           xmlns:xsdi="http://www.w3.org/2001/XMLSchema-instance"
           xsdi:schemaLocation="http://www.emobility.org emobility.xsd">
    <operator>
        <name>Tesla</name>
        <email>contact@tesla.com</email>
        <phone>0018885183752</phone>
        <chargingparks>
            <chargingpark>
                <id>1</id>
                <address>
                    <city>St. Valentin</city>
                    <zip>4300</zip>
                    <street>Rasthausstraße</street>
                    <streetNr>3</streetNr>
                    <federalState>NÖ</federalState>
                    <country>AT</country>
                </address>
                <chargingstations>
                    <chargingstation>
                        <id>1</id>
                        <connector>Type 2</connector>
                        <maxPowerOut>250</maxPowerOut>
                        <pricePerKwh>0.28</pricePerKwh>
                        <inUse>false</inUse>
                    </chargingstation>
                    <chargingstation>
                        <id>2</id>
                        <connector>Type 2</connector>
                        <maxPowerOut>250</maxPowerOut>
                        <pricePerKwh>0.28</pricePerKwh>
                        <inUse>false</inUse>
                    </chargingstation>
                    <chargingstation>
                        <id>3</id>
                        <connector>Type 2</connector>
                        <maxPowerOut>250</maxPowerOut>
                        <pricePerKwh>0.28</pricePerKwh>
                        <inUse>false</inUse>
                    </chargingstation>
                </chargingstations>
            </chargingpark>
        </chargingparks>
        <members>
            <member>
                <id>1</id>
                <firstname>Michael</firstname>
                <lastname>Hitzker</lastname>
                <address>
                    <city>Tragwein</city>
                    <zip>4284</zip>
                    <street>Hohensteg</street>
                    <streetNr>5</streetNr>
                    <federalState>OÖ</federalState>
                    <country>AT</country>
                </address>
                <email>michael@michaelhitzker.at</email>
                <phone>069917055634</phone>
                <active>true</active>
                <dateRegistered>1569490169001</dateRegistered>
            </member>
        </members>
        <employees>
            <employee>
                <id>1</id>
                <firstname>Max</firstname>
                <lastname>Mustermann</lastname>
                <address>
                    <city>Wien</city>
                    <zip>1010</zip>
                    <street>Musterstrasse</street>
                    <streetNr>31</streetNr>
                    <federalState>Wien</federalState>
                    <country>AT</country>
                </address>
                <email>max@mustermann.at</email>
                <phone>0664300333</phone>
                <dateJoined>1505858400000</dateJoined>
                <quitted>false</quitted>
                <discount>20</discount>
            </employee>
        </employees>
        <address>
            <city>Palo Alto</city>
            <zip>94020</zip>
            <street>Deer Creek Rd</street>
            <streetNr>3500</streetNr>
            <federalState>CA</federalState>
            <country>US</country>
        </address>
    </operator>
    <chargeManager>
        <charges>
            <charge>
                <startDate>1565669183000</startDate>
                <endDate>1565669483000</endDate>
                <duration>5</duration>
                <kwhCharged>20.83</kwhCharged>
                <pricePerKwh>0.28</pricePerKwh>
                <total>5.83</total>
                <userId>1</userId>
                <parkId>1</parkId>
                <stationId>1</stationId>
            </charge>
        </charges>
        <activeCharges></activeCharges>
    </chargeManager>
</emobility>
